import { createServiceRoleClient } from "@/lib/supabase/server";
import { Competition } from "@/components/CompetitionCard";

// Omit the ID as it's generated by DB
export type CreateCompetitionDTO = Omit<Competition, "id">;

export const competitionService = {
  /**
   * Retrieve competitions with pagination
   */
  async getCompetitions(limit: number = 10, offset: number = 0): Promise<Competition[]> {
    const supabase = await createServiceRoleClient();
    const { data, error } = await supabase
      .from("competitions")
      .select("*")
      .order("created_at", { ascending: false })
      .range(offset, offset + limit - 1);



    if (error) throw new Error(error.message);
    return data || [];
  },

  /**
   * Retrieve a single competition by ID
   */
  async getCompetitionById(id: string): Promise<Competition> {
    const supabase = await createServiceRoleClient();
    const { data, error } = await supabase
      .from("competitions")
      .select("*")
      .eq("id", id)
      .single();

    if (error) throw new Error(error.message);
    return data;
  },

  /**
   * Create a new competition
   */
  async createCompetition(dto: CreateCompetitionDTO): Promise<Competition> {
    const supabase = await createServiceRoleClient();
    const { data, error } = await supabase
      .from("competitions")
      .insert([dto])
      .select()
      .single();

    if (error) throw new Error(error.message);
    return data;
  },

  /**
   * Update an existing competition
   */
  async updateCompetition(id: string, dto: Partial<CreateCompetitionDTO>): Promise<Competition> {
    const supabase = await createServiceRoleClient();
    const { data, error } = await supabase
      .from("competitions")
      .update(dto)
      .eq("id", id)
      .select()
      .single();

    if (error) throw new Error(error.message);
    return data;
  },

  /**
   * Delete a competition
   */
  async deleteCompetition(id: string): Promise<void> {
    const supabase = await createServiceRoleClient();
    const { error } = await supabase
      .from("competitions")
      .delete()
      .eq("id", id);

    if (error) throw new Error(error.message);
  }
};
